Use URL parsing for Mission ID upload
samfundev/KTANE-Bombs pull request #67
Opened 2022-11-20 07:09 UTC by Flamanis

Parse Mission ID as int or as a URL. Use parsed URL to get the id paramstring.

Current Regex requires a character after the id numbers. If no character is found, then even a valid string will fail.

2022-11-20 14:46 UTC, Luminoscity commented
No need to revert my commit, you actually need that. It doesn't work for this link without it `https://steamcommunity.com/sharedfiles/filedetails/?id=1517753537/`
The slash gets sees as part of the id and then it fails the isOnlyDigits check.

2022-11-20 15:13 UTC, Luminoscity requested changes
Need to put that back to conform to Sam's prettier standards and to handle the common single slash case.

2022-11-20 16:30 UTC, Flamanis commented
It works perfectly fine on my end. I use the standard URL class, it handles it perfectly.

2022-11-20 16:39 UTC, Flamanis commented
After looking through the workshop. Steam does not serve a page with a slash after the id. The test is mostly a moot point. But, it's not really extra code to run after the user already failed. It will very likely never have a positive, but eh.

2022-12-01 10:12 UTC, Luminoscity requested changes

2022-12-01 10:12 UTC, Luminoscity commented on src/lib/controls/Input.svelte
> +			input.setCustomValidity(typeof validity === 'string' ? validity : validity ? '' : 'Invalid value');
Breaks some validated inputs, like "Variant of" and "Mission Pack" and many other inputs on mission edit page (allows submission of form when invalid data is present in the box but silently replaces the input with the last valid input)

2022-12-04 13:27 UTC, merged