Logfile uploads
samfundev/KTANE-Bombs pull request #95
Opened 2023-02-24 14:50 UTC by Luminoscity

1) Uploading a new mission with a logfile is now done with a link instead of a file upload, the link used to create the mission page is saved in the database and displayed on a mission page (editable from the edit page). #37  https://discord.com/channels/887088776818602055/1004869408734335056/1073582857877999776
2) Fixed the page flash on a /user/<name> page when you click on your own name or refresh the page (flash only happened if "By Role" was your preference)
3) Pasting a logfile in the Proof box, when uploading a new solve, grabs the mission name and time remaining on the bomb down to hundredths of a second. https://discord.com/channels/887088776818602055/1004869408734335056/1073798669658226748
4) Date Added fields for missions and mission packs (editable from the edit pages) https://discord.com/channels/887088776818602055/1004869408734335056/1073906060080984125
    - New mission and mission pack uploads record the Data Added automatically.
5) Sorting missions by Date Added #94
6) Mission [[UPDATE]] pages (see below, these pages are created when uploading a logfile to replace a mission's parameters) now show the solves of the mission they are updating.
![image](https://user-images.githubusercontent.com/10985005/221423420-7cd875f3-7ad6-43b7-9e44-19088e6f7fc5.png)

7) The new kind of TP solves (with proof link and time) don't count as EFMs on the Mission card, https://discord.com/channels/887088776818602055/887088777409986572/1078417668324999198

The new logfile field and both dateAdded field will be populated using some node.js scripts shortly after merging this.

2023-02-26 01:29 UTC, samfundev requested changes

2023-02-26 08:53 UTC, Luminoscity commented on prisma/schema.prisma
> +  dateAdded Int?
I wasn't aware you could do that. I'm not sure how I would store DateTime objects in a JSON file so we can do the upcoming update to all missions and mission packs.

2023-02-26 08:59 UTC, Flamanis commented on prisma/schema.prisma
> +  dateAdded Int?
https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#datetime
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toJSON

2023-02-28 18:51 UTC, samfundev requested changes

2023-02-28 18:51 UTC, samfundev commented on src/lib/util.ts
> +type DateSortable = ID<Mission> | ID<MissionPack> | ID<Completion>;
You could make this type more generic, allowing it support anything with an ID and a dateAdded.
```suggestion
type DateSortable = { id: number, dateAdded: Date | null };
```

2023-03-01 08:46 UTC, merged